#+TITLE: Emacs Font Config
#+AUTHOR: Mike Hostetler
#+OPTIONS: toc:nil
#+options: num:0
#+OPTIONS: ^:nil
#+PROPERTY:   header-args+ :comments both
#+PROPERTY:   header-args+ :mkdirp yes
#+PROPERTY:   header-args+ :tangle "~/.emacs.d/personal/font.el"
#+bind: org-html-htmlize-output-type csspuA
#+OPTIONS: toc:2
#+SETUPFILE: https://fniessen.github.io/org-html-themes/setup/theme-readtheorg.setup

* Prologue

Generally fonts on the web or in applications aren't a big deal, but some reason I spend a lot of time finding an tweaking fonts in my editor. This is a story of how I set that up.

* Unicode

First and really the most important -- set UTF-8 everywhere

#+begin_src lisp
(set-language-environment "UTF-8")
(set-default-coding-systems 'utf-8-unix)

#+end_src

* Font selection

I got back and forth of what I want for a default font. And once in a while I have to move this config to other machines and they may not have all my configs. So below you can see what I have tried... none of these are bad, but I've moved for some reason.

Basically this little snippet will look if that font name exists and, if so, will set it as the default. Note that I do this over and over again, replacing the default font until it gets to the end.

[[https://dejavu-fonts.github.io/][DejaVu Sans Mono]]


#+begin_src elisp
(when (member "DejaVu Sans Mono" (font-family-list))
  (set-face-attribute 'default nil :font "DejaVu Sans Mono" :height 140 :weight 'normal))

#+end_src

#+RESULTS:

[[https://github.com/adobe-fonts/source-code-pro][Source Code Pro]] -- I used this the longest. One of it's problems is that it doesn't have all the unicode characters in it (see below of that fix). Another is that it's hard to read sometimes, and making it bigger can make it worse. I like it at 125 and really no other size

#+begin_src elisp
(when (member "Source Code Pro" (font-family-list))
  (set-face-attribute 'default nil :font "Source Code Pro" :height 125 :weight 'normal))

#+end_src

[[https://github.com/IBM/plex][IBM Plex]] -- wait? IBM has a font?!? Yes it does. Lots of them, actually, under the Plex name. It's certainly very corporate looking, but apparently they use this corporate wide. Not only does it look nice and scale well, it seems to be complete as far as weight, italic, etc. Anyway this is my latest font try and so far so good.

#+begin_src elisp
(when (member "IBM Plex Mono" (font-family-list))
  (set-face-attribute 'default nil :font "IBM Plex Mono" :height 140 :weight 'normal))

#+end_src

#+RESULTS:

** Let's get complicated

Sometimes in writing, I may want to use a Sans-Serif font... this function will let me do that

#+begin_src elisp
(defun mikeh-buffer-face-mode-sans ()
  "Sets a sans-serif font in current buffer"
  (interactive)
  (setq buffer-face-mode-face '(:family "IBM Plex Arabic" :height 135 :weight 'normal))
  (buffer-face-mode))

#+end_src


* Lastly... more Unicode

Seems familiar? Just like [[*Unicode][in Unicode]] but different -- that was about what we use, not what we display it. Symbola is pretty ugly but (as the name states) it has a complete UTF-8 state. Prepending this allows us to view all characters.

I should note that I don't deal with multiple languages and symbols often, but it's best to prepare yourself when before you find yourself in that world

#+begin_src lisp
  (when (member "Symbola" (font-family-list))
    (set-fontset-font t 'unicode "Symbola" nil 'prepend))

#+end_src
